---
# roles/server-base/tasks/main.yml

  - name: Upgrade all packages to the latest version
    apt:
      name: "*"
      state: latest

  - name: Update all packages to the latest version
    apt:
      upgrade: dist

  - name: Run the equivalent of "apt-get update" as a separate step
    apt:
      update_cache: yes

  - name: Only run "update_cache=yes" if the last one is more than 3600 seconds ago
    apt:
      update_cache: yes
      cache_valid_time: 3600

  - name: install requirements
    apt:
      name: '{{ item }}'
      state: present
    with_items:
     - htop
    become: yes
  